apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis
  namespace: whisper
spec:
  deploymentPlan:
    jolokiaAgentEnabled: false
    journalType: nio
    managementRBACEnabled: true
    messageMigration: false
    persistenceEnabled: false
    requireLogin: false
    size: 2
  adminPassword: admin
  adminUser: admin
  console:
    expose: true
---
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisAddress
metadata:
  name: audios
  namespace: whisper
spec:
  addressName: audios
  queueName: audios
  routingType: anycast
  password: admin
  user: admin
